name: CI

on:
  push:
    branches: [ master ]

jobs:
  integrate:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --no-cache -t checktor/face-amnesia:latest .
      - name: Test Docker image
        run: docker run checktor/face-amnesia:latest /bin/bash -c "./home/face_amnesia/test.sh"
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish container
        run: docker push checktor/face-amnesia:latest
