name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t face-amnesia .
      - name: Test Docker image
        run: docker run -it face-amnesia ./home/face_amnesia/test.sh
      - name: Login to GitHub registry
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      - name: Push to Docker registry
        run: docker push face-amnesia
