name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  integrate:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t checktor/face-amnesia:latest .
      - name: Test Docker image
        run: docker run checktor/face-amnesia:latest /bin/bash -c "./home/face_amnesia/test.sh"
      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish container
        run: docker push checktor/face-amnesia:latest
