name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/checktor/face_amnesia/face-amnesia:latest .
      - name: Test Docker image
        run: docker run docker.pkg.github.com/checktor/face_amnesia/face-amnesia:latest /bin/bash -c "cd /home/face_amnesia && ./test.sh"
      - name: Login to GitHub registry
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Push to GitHub registry
        run: docker push docker.pkg.github.com/checktor/face_amnesia/face-amnesia:latest
